platform :ios, '12.0'
use_frameworks!

target 'YYImageLabel_Example' do
  pod 'Masonry'
  pod 'YYImageLabel', :path => '../'

  target 'YYImageLabel_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
